[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
build_flags =
    -Isrc
    -Isrc/interfaces
    -Isrc/shared
    -Isrc/shared/stft
    -Isrc/shared/pre_estimation
    -Isrc/shared/noise_estimation
    -Isrc/shared/post_estimation
    -Isrc/shared/gain_estimation
    -Isrc/shared/utils
    -Isrc/processors
    -Isrc/processors/denoiser
    -Isrc/processors/adaptivedenoiser
    -Iinclude
    -D__FPU_PRESENT=1
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
